# Defines our Vagrant environment
#
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # create mgmt node
  config.vm.define :mgmt do |mgmt_config|
      mgmt_config.vm.box = "centos/7"
      mgmt_config.vm.hostname = "mgmt"
      mgmt_config.vm.network :private_network, ip: "10.0.15.15"
      mgmt_config.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
        vb.name= "mgmt"
      end
      mgmt_config.vm.provision :shell, path: "bootstrap.sh"
  end

  # create load balancer
  config.vm.define :lb do |lb_config|
      lb_config.vm.box = "centos/7"
      lb_config.vm.hostname = "lb"
      lb_config.vm.network :private_network, ip: "10.0.15.16"
      lb_config.vm.network "forwarded_port", guest: 80, host: 8080
      lb_config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.name= "lb"
      end
      lb_config.vm.provision :shell, path: "abootstrap.sh"
  end

end
