# Defines our Vagrant environment
#
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # create mgmt node
  config.vm.define :jenkins do |mgmt_config|
      mgmt_config.vm.box = "centos/7"
      mgmt_config.vm.hostname = "jenkins"
      mgmt_config.vm.network :private_network, ip: "10.0.11.11"
      mgmt_config.vm.network "forwarded_port", guest: 80, host: 8080
      mgmt_config.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
        vb.name= "jenkins"
      end
      mgmt_config.vm.provision :shell, path: "bootstrap.sh"
  end
end
